# -*- coding: utf-8 -*-
"""20201116_PackagingTest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m0iGg7dYZfhM8FPnf6GeAEvFakDN8dSv
"""

class TestClass:
  def __init__(self, code, name):
    self.code = code
    self.name = name


class Country:
  def __init__(self, country_name):
    self.country_name = country_name
 
 
class City(Country):
  def __init__(self, country_name, city_name):
    super().__init__(country_name)
    self.city_name = city_name


class NewStyleClassBase(object):
  def test_method(self, msg):
    print('NewStyleClassBase: {}'.format(msg))
 
 
class NewStyleClass(NewStyleClassBase):
  def test_method(self, msg):
    print('NewStyleClass: {}'.format(msg))
    super().test_method(msg)